#!/bin/bash

set -euo pipefail
set -x

IFS=',' read -ra fuzzers <<< $1
IFS=',' read -ra cves <<< $2
CMDS=()

for fuzzer in "${fuzzers[@]}"
do
  for cve in "${cves[@]}"
  do
    project="$(cat cve.json | jq -er --arg cve ${cve} '.[] | select(.cve == $cve) | .project')"
    CMDS+=("docker buildx build --build-arg CVE=${cve} --build-arg TAG=$(date -I) --build-arg SAN='-nosan' --file docker/${fuzzer}/${project}.Dockerfile --tag afl1007-artifact/${fuzzer}/${cve}:$(date -I)-nosan .")
  done
done

xpanes -c "{}" "${CMDS[@]}"
