#!/bin/bash

set -euo pipefail

IFS=',' read -ra fuzzers <<< $1
IFS=',' read -ra cves <<< $2
CMDS=()

for fuzzer in "${fuzzers[@]}"
do
  for cve in "${cves[@]}"
  do
    CMDS+=("docker buildx build --build-arg CVE=${cve} --build-arg TAG=$(date -I) --file docker/${fuzzer}/libxml2.Dockerfile --tag afl1007-artifact/${fuzzer}/${cve}:$(date -I) .")
  done
done

xpanes -c "{}" "${CMDS[@]}"
