#!/bin/bash

set -euxo pipefail

#
# entrypoint <cve> <mintime> <maxtime> <timeout>
#

CVE=$1
MINTIME=$2
MAXTIME=$3
TIMEOUT=$4
CMD_TEMPLATE="$(cat cve.json | jq -er --arg cve ${CVE} '.[] | select(.cve == $cve) | .command')"

if [ ! -d "/in" ]; then
    echo "Input directory not found!"
    exit 1
fi

if [ ! -d "/out" ]; then
    echo "Output directory not found!"
    exit 1
fi

cp -r /in /tmp/in

timeout "${MAXTIME}" /aflgo/afl-2.57b/afl-fuzz -i /tmp/in -o /tmp/out -m none -z exp -c "${MINTIME}" -t "${TIMEOUT}" -- ${CMD_TEMPLATE} || true

/bin/postprocess
