name: 'Build and Push'

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-fuzzer:
    strategy:
      matrix:
        fuzzer: [aflgo, afl1007]
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Docker meta'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.fuzzer }}
      - name: 'Set up QEMU'
        uses: docker/setup-qemu-action@v3
      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: 'Build and push'
        uses: docker/build-push-action@v5
        with:
          cache-from: type=ghq
          cache-to: type=gha,mode=max
          file: docker/${{ matrix.fuzzer }}/Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  build-and-push-targets:
    needs: [build-and-push-fuzzer]
    strategy:
      matrix:
        fuzzer: [aflgo, afl1007]
        target: [
          {project: 'libxml2', cve: '2017-5969'}
        ]
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Docker meta'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.fuzzer }}/${{ matrix.target.cve }}
      - name: 'Docker base meta'
        id: basemeta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.fuzzer }}
      - name: 'Get base tag'
        id: basetag
        run: |
          tag=$(echo ${{ steps.basemeta.outputs.tags }} | cut -d: -f2)
          echo "tag=${tag}" >> $GITHUB_OUTPUT
      - name: 'Set up QEMU'
        uses: docker/setup-qemu-action@v3
      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: 'Build and push'
        uses: docker/build-push-action@v5
        with:
          build-args: |
            CVE=${{ matrix.target.cve }}
            TAG=${{ steps.basetag.outputs.tag }}
          cache-from: type=ghq
          cache-to: type=gha,mode=max
          file: docker/${{ matrix.fuzzer }}/${{ matrix.target.project }}.Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
