name: 'Build, Push and Run'

on:
  push:
    branches:
      - main
    paths:
      - 'docker/**'
      - 'target/**'
      - 'experiment/**'
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-fuzzer:
    strategy:
      matrix:
        fuzzer: [aflgo, afl1007]
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Docker meta'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.fuzzer }}
      - name: 'Set up QEMU'
        uses: docker/setup-qemu-action@v3
      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: 'Build and push'
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: docker/${{ matrix.fuzzer }}/Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}