name: 'Lint and Format'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  hadolint:
    name: Hadolint Action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: '*Dockerfile'
          recursive: true
          ignore: DL3008,DL3013
